# Generated by Django 2.1.3 on 2018-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiadocDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_brief', models.CharField(max_length=10)),
                ('doc_type', models.CharField(max_length=10)),
                ('doc_number', models.IntegerField()),
                ('doc_date', models.DateField()),
                ('doc_description', models.TextField()),
            ],
        ),
    ]
